#!/bin/bash

if [ -n "$1" ]; then

	bash $HOME/os-code-server/Scripts/$1

else
    echo "NOTE: To initialize a new code you must be authenticated with a cluster in your terminal session"
    echo ""
	echo "Options available: "
    echo "  Create (Creates a new code server on currently authenticated openshift cluster)"
    echo "  Status (Shows status of code server)"
    echo "  Destroy (Destroys the most recently deployed code server)"
    echo "  Update"

fi