#!/bin/bash

if [ -n "$1" ]; then

	bash $1

else

	echo "Options available: "
    echo "  Create (Creates a new code server on currently authenticated openshift cluster)"
    echo "  Status (Shows status of code server)"
    echo "  Destroy (Destroys the most recently deployed code server"

fi