#!/bin/bash
oc whoami --show-token > $HOME/.usertoken.txt
oc whoami --show-server > $HOME/.userserver.txt
oc login --token=$(cat $HOME/.token.txt) --server=$(cat $HOME/.server.txt) --insecure-skip-tls-verify="false" > /dev/null 2>&1 || { echo "login not ok. Exit code: $?"; exit 1; }

oc project os-code > /dev/null 2>&1

echo "Build status:"

oc -n os-code get build -l "app=code-server"

echo ""

echo "Code server is accepting traffic at:"

echo "https://$(oc get routes code-server -o=jsonpath='{ .spec.host }')"

echo ""

echo "The password to sign in is:"

oc exec $(oc -n os-code get pod -l "app=code-server" -o jsonpath='{.items[*].metadata.name}') -- cat /home/coder/.config/code-server/config.yaml | grep password:

oc login --token=$(cat $HOME/.usertoken.txt) --server=$(cat $HOME/.userserver.txt) > /dev/null 2>&1
rm -rf $HOME/.usertoken.txt $HOME/.userserver.txt > /dev/null 2>&1