#!/bin/bash
oc whoami --show-token > /dev/null 2>&1
status=$?
if [ ${status} -eq 0 ]; then
    oc whoami --show-token | base64 > $HOME/.usertoken.txt
    oc whoami --show-server | base64 > $HOME/.userserver.txt
    login=true
fi
echo "Pushing..."
oc login --token=$(cat $HOME/.token.txt | base64 --decode) --server=$(cat $HOME/.server.txt | base64 --decode) --insecure-skip-tls-verify="false" > /dev/null 2>&1 || { echo "login not ok. Exit code: $?"; exit 1; }
oc project os-code-$(whoami) > /dev/null 2>&1
rsync -a --rsh='oc rsh' $(pwd) $(oc -n os-code-$(whoami) get pod -l "app=code-server" -o jsonpath='{.items[*].metadata.name}'):/home/coder/projects > /dev/null 2>&1
oc logout > /dev/null 2>&1
if [ "${login}" == "true" ]; then
    oc login --token=$(cat $HOME/.usertoken.txt | base64 --decode) --server=$(cat $HOME/.userserver.txt | base64 --decode) > /dev/null 2>&1
    rm -rf $HOME/.usertoken.txt $HOME/.userserver.txt > /dev/null 2>&1
fi
echo "Complete"
exit 0;